from . import hr_employee
from . import product
from . import sale_order
from . import res_partner
from . import purchase_order
from . import fleet_vehicle
from . import gas_tracking
from . import gas_transaction
from . import gas_tracking_config
